### PR TITLE
Replaced nette/nette with nette/di, removed dependency on kdyby/events

### PR DESCRIPTION
**Pull request by MartkCz**

### CODE REVIEW

**Comment by mishak87** [comment]
Hi @AntikCz thanks for the pull request. Could you please explain your reasoning for this pull?

**Comment by AntikCz** [comment]
Your library needs only nette/di, nette/utils (I forgot add this to composer) and kdyby/doctine, other dependencies are unnecessary. If you have nette/nette in composer, it downloads all packages from nette (nette/bootstrap, nette/caching, nette/finder, ...).

**Comment by mishak87** [comment]
I understand the nette but why `kdyby/events`?

**Comment by mishak87** [comment]
`kdyby/events` is definitely necessary for binding listeners it is used in [config](https://github.com/rixxi/gedmo/blob/master/src/Rixxi/Gedmo/DI/config/gedmo.neon).

**Comment by AntikCz** [comment]
You have right, I did not watch into the file

**Comment by mishak87** [comment]
Thank you! Released as 1.0.7

**Pull request merged**
